[context.deploy-preview.environment]
VERCEL_URL = "NEXTAUTH_URL_PLACEHOLDER"

[build]
command = "sed -i 's/NEXTAUTH_URL_PLACEHOLDER/$DEPLOY_PRIME_URL/g' netlify.toml && npm run build"
functions = "out_functions"
publish = "out_publish"

[dev]
functions = "out_functions"
publish = "out_publish"
# We manually set the framework to static, otherwise Netlify automatically
# detects Next.js and redirects do not work.
# Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
framework = "#static"
